---
layout: cv
title: Corbin Wamsley's CV
---
# Corbin Wamsley

**Major in Computer Science and Minor in Finance** at BYU-Idaho.

<wam21006@byui.edu> | [My Linked In page](www.linkedin.com/in/corbin-wamsley-0610ba263)

---

## 🎓 Education

**Bachelor of Computer Science and Minor in Finance** | GPA: 3.9  
Brigham Young University - Idaho | Rexburg, ID  
*September 2022 - April 2028*

---

## 🛠️ Skills & Certifications

* **Programming Languages:** Fluent in Python and Spanish, experienced in SQL and C#.
* **Soft Skills:** Critical Thinking, Telecommunication, Public Speaking, Team Coordination, Leader, Problem Solving, Quick learner.

---

## 🌟 Projects & Achievements (From Resume Content)

* Recognized a lack of inclusion for international students and coordinated with five teams to organize an event promoting support and engagement within the Computer Science department, allowing more students to be included.
* Collaborated with a team of 4 developers to build a web application in **HTML, CSS, and Javascript** connecting community members with service opportunities.
* Achieved **2nd place** in the Human Progression category at schoolwide hackathon with 30+ teams, completing project within 24 hours.
* Learned to use **C#** in 2 weeks.

---

## 💼 Experience

### Area Leader/Team Leader/Trainer
**Church of Jesus Christ of Latter-Day Saints** | Las Vegas, NV  
*July 2023 - June 2025*

* Oversaw performance of 30+ areas with over 90+ employees and worked to readily improve metrics.
* Mentored and trained two new hires, building confidence and leadership potential by addressing individual concerns through one-on-one guidance and shadowing, resulting in future leaders.
* Identified declining performance metrics and implemented weekly team meetings, resulting in improvements exceeding 200%.

### Head Coach
**Aberdeen Swim Team** | Atlanta, GA  
*April 2023 - June 2023*

* Coached and trained 100+ swimmers to improve performance and abilities.
* Coordinated with 7 other teams to set up swim meets for competition.
* Identified gaps in coaches' training and developed skills through weekly meetings and shadowing, ensuring positive perception from swimmers.
* Inspired and led team to place **Third** at championship swim meet even after major loss of athletes from previous year through focusing one-on-one with swimmers and tailoring practices to needs.

### Shipping Coordinator
**Cables And Kits** | Atlanta, GA  
*September 2021 - June 2022*

* Oversaw order fulfillment, ensuring timely packaging and quality control.
* Provided online customer support, resolving product inquiries and shipment issues.
<!-- ### Footer

Last updated: May 2013 -->